# Generated by Django 3.0.2 on 2020-01-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
